# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
 
   branches: [ "main" ]
jobs:
 lint-staticChecks-test-build:
   if: startsWith(github.head_ref, 'task/')
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
    # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

     - name: Setup JDK 1.8
       uses: ./.github/mini_flows/s2_setup_jdk

     - name: Mandatory File Changes
       uses: ./.github/mini_flows/s1_mandatory_filechanges

     - name: Run lint tests and Upload results
       uses: ./.github/mini_flows/s3_lint

     - name: Static Code Check Via detekt
       uses: ./.github/mini_flows/s4_detekt

     - name: Static Code Check Via checkstyle
       uses: ./.github/mini_flows/s5_checkstyle

     - name: Unit Tests (DEBUG AND RELEASE)
       uses: ./.github/mini_flows/s6_test

     - name: Build Code
       uses: ./.github/mini_flows/s7_build
       # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello Sorath, World!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test sorath task, and deploy your project.
